apiVersion: apps/v1
kind: Deployment
metadata:
        name: quote-deployment
        labels:
           app: quote

spec:
        replicas: 2
        selector:
                matchLabels:
                         app: quote
        template:
                metadata:
                        labels:
                                app: quote
                spec:
                    containers:
                            - name: quote-app
                              image: vijaydocker404/quote-app:v1
                              ports:
                                      - containerPort: 80

