apiVersion: v1
kind: Service 
metadata:
        name: quote-service
        labels:
                app: quote
spec:
        selector:
                app: quote
        ports:
                - protocol: TCP
                  port: 80
                  targetPort: 80
        type: LoadBalancer 
